import { Controller, Get, Post, Body, Patch, Param, Delete, HttpCode, HttpStatus, BadRequestException, ParseUUIDPipe, Query } from '@nestjs/common';
import { TaskService } from './task.service';
import { CreateTaskDto } from './dto/create-task.dto';
import { UpdateTaskDto } from './dto/update-task.dto';
import { GetTaskDTO } from './dto/get-task.dto';
import { Task } from './entities/task.entity';
import { plainToInstance } from 'class-transformer';
import { GenData } from './interface/gen-data.interface';
import { AutoGenDTO } from './dto/autogen.dto';

@Controller('api')
export class TaskController {
  constructor(private readonly taskService: TaskService) { }

  @Post("tasks/auto-gen-data")
  @HttpCode(HttpStatus.OK)
  async getAutoGeneratedData(@Body() taskBody: AutoGenDTO): Promise<GenData> {

    return await this.taskService.getAutoGeneratedData(taskBody)
  }

  @Get("tasks")
  async getAlltasks(@Query('cat') category: string, @Query('pr') priority: string): Promise<GetTaskDTO[]> {

    return await this.taskService.getAllTasks(category == 'any' ? undefined : category, priority == 'any' ? undefined : priority);
  }
 
  @Get("tasks/:id")
  async getTask(@Param("id") id: string): Promise<GetTaskDTO | null> {
    return plainToInstance(GetTaskDTO, await this.taskService.getTask(id))
  }

  @Post("tasks")
  async createTask(@Body() taskBody: CreateTaskDto): Promise<Task> {
    console.log(taskBody);
    const dateTime: Date | undefined = taskBody.dateTime ? new Date(taskBody.dateTime) : undefined;
    return await this.taskService.createTask({...taskBody, dateTime})
  }

  @Delete("tasks/:id")
  @HttpCode(HttpStatus.NO_CONTENT)
  async deleteTask(@Param("id", ParseUUIDPipe) id: string): Promise<void> { 
    return await this.taskService.deleteTask(id)
  }

  @Patch("tasks/:id")
  async patchTask(@Param("id", ParseUUIDPipe) id: string, @Body() dto: UpdateTaskDto): Promise<Task | undefined> {
    return await this.taskService.patchTask(id, dto);
  }

}